# **Importing libraries**

In [1]:
import csv
import random
import math
import numpy as np
import pandas as pd

# **Loading the files**

In [2]:
dataset=pd.read_csv("IPL.csv")

# **Splitting of dataset**

In [3]:
x = dataset.iloc[:, 7:-1].values
y = dataset.iloc[:, -1].values

# **Adding biased term**

In [4]:
one = np.ones((len(x), 1))
x = np.append(one, x, axis=1)
print(x)

[[  1.   1.   0. ...   0.   0.   0.]
 [  1.   1.   0. ...   0.   0.   0.]
 [  1.   2.   0. ...   0.   0.   0.]
 ...
 [  1. 128.   7. ...   0.  47.  12.]
 [  1. 129.   7. ...   0.  47.  13.]
 [  1. 129.   8. ...   1.  47.  13.]]


In [5]:
y = np.array(y).reshape((len(y),1))
print(y.shape)

(76014, 1)


# **Powers**

In [6]:
y1=(x[:,1])
y1=np.power(y1,2)
y1 = np.array(y1).reshape((len(y1),1))
y2=(x[:,2])
y2=np.power(y2,2)
y2 = np.array(y2).reshape((len(y2),1))
y3=(x[:,3])
y3=np.power(y3,2)
y3 = np.array(y3).reshape((len(y3),1))
y4=(x[:,4])
y4=np.power(y4,2)
y4 = np.array(y4).reshape((len(y4),1))
y5=(x[:,5])
y5=np.power(y5,2)
y5 = np.array(y5).reshape((len(y5),1))
y6=(x[:,6])
y6=np.power(y6,2)
y6 = np.array(y6).reshape((len(y6),1))
y7=(x[:,7])
y7=np.power(y7,2)
y7 = np.array(y7).reshape((len(y7),1))

#y8=(x[:,1])
#y8=np.power(y8,3)
#y8 = np.array(y8).reshape((len(y8),1))
#y9=(x[:,2])
#y9=np.power(y9,3)
#y9 = np.array(y9).reshape((len(y9),1))
#y10=(x[:,3])
#y10=np.power(y10,3)
#y10= np.array(y10).reshape((len(y10),1)) 
#y11=(x[:,4])
#y11=np.power(y11,3)
#y11= np.array(y11).reshape((len(y11),1))
#y12=(x[:,5])
#y12=np.power(y12,3)
#y12= np.array(y12).reshape((len(y12),1))
#y13=(x[:,6])
#y13=np.power(y13,3)
#y13= np.array(y13).reshape((len(y13),1))
#y14=(x[:,7])
#y14=np.power(y14,3)
#y14=np.array(y14).reshape((len(y14),1))

#y15=(x[:,1])
#y15=np.power(y15,4)
#y15= np.array(y15).reshape((len(y15),1))
#y16=(x[:,2])
#y16=np.power(y16,4)
#y16= np.array(y16).reshape((len(y16),1))
#y17=(x[:,3])
#y17=np.power(y17,4)
#y17= np.array(y17).reshape((len(y17),1)) 
#y18=(x[:,4])
#y18=np.power(y18,4)
#y18= np.array(y18).reshape((len(y18),1))
#y19=(x[:,5])
#y19=np.power(y19,4)
#y19= np.array(y19).reshape((len(y19),1))
#y20=(x[:,6])
#y20=np.power(y20,4)
#y20= np.array(y20).reshape((len(y20),1))
#y21=(x[:,7])
#y21=np.power(y21,4)
#y21=np.array(y21).reshape((len(y21),1))


In [7]:
x = np.append(x, y1, axis=1)
x = np.append(x, y2, axis=1)
x = np.append(x, y3, axis=1)
x = np.append(x, y4, axis=1)
x = np.append(x, y5, axis=1)
x = np.append(x, y6, axis=1)
x = np.append(x, y7, axis=1)

#x = np.append(x, y8, axis=1)
#x = np.append(x, y9, axis=1)
#x = np.append(x, y10, axis=1)
#x = np.append(x, y11, axis=1)
#x = np.append(x, y12, axis=1)
#x = np.append(x, y13, axis=1)
#x = np.append(x, y14, axis=1)

#x = np.append(x, y15, axis=1)
#x = np.append(x, y16, axis=1)
#x = np.append(x, y17, axis=1)
#x = np.append(x, y18, axis=1)
#x = np.append(x, y19, axis=1)
#x = np.append(x, y20, axis=1)
#x = np.append(x, y21, axis=1)
print(x)


[[1.000e+00 1.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.000e+00 1.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.000e+00 2.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 ...
 [1.000e+00 1.280e+02 7.000e+00 ... 0.000e+00 2.209e+03 1.440e+02]
 [1.000e+00 1.290e+02 7.000e+00 ... 0.000e+00 2.209e+03 1.690e+02]
 [1.000e+00 1.290e+02 8.000e+00 ... 1.000e+00 2.209e+03 1.690e+02]]


# **splitting dataset randomly**

In [8]:
def train_test_split(x, y, split):

    #randomly assigning split% rows to training set and rest to test set
    indices = np.array(range(len(x)))
    
    train_size = round(split * len(x))

    random.shuffle(indices)

    train_indices = indices[0:train_size]
    test_indices = indices[train_size:len(x)]

    x_train = x[train_indices, :]
    x_test = x[test_indices, :]
    y_train = y[train_indices, :]
    y_test = y[test_indices, :]

    return x_train,y_train, x_test, y_test
  


In [9]:
split = 0.7
X_train, Y_train, X_test, Y_test = train_test_split(x, y, split)
#print(x_train)
#print(y_train)
#print(x_test)
#print(y_test)

# **Beta value prediction**

In [10]:
def normal_equation(x, y):
    beta = np.dot((np.linalg.inv(np.dot(x.T,x))), np.dot(x.T,y))

    return beta
def predict(X_test, beta):
    return np.dot(X_test, beta)

In [11]:
beta = normal_equation(X_train, Y_train)
print(beta)
predictions= predict(X_test, beta)
prediction = predict([[1, 201, 3, 19, 71, 2, 82, 17, np.power(201,2), np.power(3,2), np.power(19,2), np.power(71,2), np.power(2,2), np.power(82,2), np.power(17,2)]], beta)

print(prediction)

[[ 1.59957693e+02]
 [ 1.22226353e+00]
 [-7.47064033e+00]
 [-6.05626481e+00]
 [-4.00587501e-02]
 [-2.81765069e+00]
 [-2.48586459e-02]
 [-6.97619478e-02]
 [-9.24171166e-04]
 [ 3.75725073e-01]
 [-3.35347030e-02]
 [-5.21523062e-05]
 [ 2.24113630e-01]
 [ 1.70361404e-04]
 [-1.32709605e-03]]
[[211.78146842]]


In [12]:
print(Y_test)

[[189]
 [121]
 [126]
 ...
 [124]
 [163]
 [150]]


# **Accuracy(R Value)**

In [13]:
def metrics(predictions, Y_test):

    #calculating mean absolute error
    MAE = np.mean(np.abs(predictions-Y_test))

    #calculating root mean square error
    MSE = np.square(np.subtract(Y_test,predictions)).mean() 
    RMSE = math.sqrt(MSE)

    #calculating r_square
    rss = np.sum(np.square((Y_test- predictions)))
    mean = np.mean(Y_test)
    sst = np.sum(np.square(Y_test-mean))
    r_square = 1 - (rss/sst)
    

    return MAE, RMSE, r_square

In [14]:
mae, rmse, r_square = metrics(predictions, Y_test)
print("Mean Absolute Error: ", mae)
print("Root Mean Square Error: ", rmse)
print("R square: ", r_square)

Mean Absolute Error:  14.715234162099584
Root Mean Square Error:  20.16504644275753
R square:  0.5241585293383991
